blueprint:
  name: Virtual Multi-Way Switch
  description: >-
    Creates a virtual multi-way switch configuration (3-way, 4-way, 5-way, etc.) where multiple 
    switches/lights can control each other. When any switch changes state, all others will match that state.
  domain: automation
  input:
    input_switches:
      name: Escolha os pontos de Iluminação
      selector:
            entity:
              domain:
                - switch
                - light
              multiple: true

trigger:
  platform: state
  entity_id: !input input_switches

action:
  - service: >
      {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
      {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
      {% endif %}
    target:
      entity_id:
        !input input_switches
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0

mode: single